version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: siem
      POSTGRES_PASSWORD: siem_pass
      POSTGRES_DB: siemdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  collector:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    ports: ["8000:8000"]
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://siem:siem_pass@db:5432/siemdb
    volumes:
      - /tmp:/tmp

  pipeline:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./pipeline:/app
      - /tmp:/tmp
    command: ["bash", "-c", "pip install -r requirements.txt && python correlator.py"]
    depends_on:
      - collector
      - db

  ui:
    build:
      context: .
      dockerfile: infra/Dockerfile.ui
    ports:
      - "3000:3000"
    depends_on:
      - collector
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  pgdata: